export interface HighlightEvent {
  month: number;
  day: number;
  category: string;
  title: string;
  description: string;
  historicalYear?: number;
  fact: string;
  quote?: string;
}

export const FUNNY_TECH_QUOTES: string[] = [
  "I'm not a great programmer; I'm just a good programmer with great habits.",
  "There are only 10 types of people in the world: those who understand binary, and those who don't.",
  "Programming is like sex: one mistake and you have to support it for the rest of your life.",
  "Software and cathedrals are much the same – first we build them, then we pray.",
  "A user interface is like a joke. If you have to explain it, it's not that good.",
  "Debugging is like being the detective in a crime movie where you are also the murderer.",
  "Code never lies, comments sometimes do.",
  "It’s not a bug, it’s an undocumented feature.",
  "In theory, theory and practice are the same. In practice, they’re not.",
  "To understand recursion, you must first understand recursion.",
  "My code doesn’t work, I have no idea why. My code works, I have no idea why.",
  "First, solve the problem. Then, write the code.",
  "Make it work, make it right, make it fast.",
  "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
  "Without requirements or design, programming is the art of adding bugs to an empty text file.",
  "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
  "Programming can be fun, so can cryptography; however they should not be combined.",
  "Deleted code is debugged code.",
  "Talk is cheap. Show me the code.",
  "The only way to learn a new programming language is by writing programs in it.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "Measuring programming progress by lines of code is like measuring airplane building progress by weight.",
  "Testing can only prove the presence of bugs, not their absence.",
  "The best code is no code at all.",
  "Before software can be reusable it first has to be usable.",
  "Copy and paste is a design error.",
  "If at first you don't succeed, call it version 1.0.",
  "I don't care if it works on your machine! We are not shipping your machine!",
  "Real programmers count from 0.",
  "A SQL query goes into a bar, walks up to two tables and asks... 'Can I join you?'",
  "Why do Java programmers have to wear glasses? Because they don't C#.",
  "I would love to change the world, but they won’t give me the source code.",
  "Optimism is an occupational hazard of programming: feedback is the treatment.",
  "A good programmer is someone who always looks both ways before crossing a one-way street.",
  "Every programmer is an author.",
  "The computer was born to solve problems that did not exist before.",
  "Hardware: The parts of a computer system that can be kicked.",
  "Software is a great combination between artistry and engineering.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The most disastrous thing that you can ever learn is your first programming language.",
  "Programming is the art of telling another human what one wants the computer to do.",
  "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
  "Simplicity is the soul of efficiency.",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "Walking on water and developing software from a specification are easy if both are frozen.",
  "One man's crappy software is another man's full-time job.",
  "The trouble with programmers is that you can never tell what a programmer is doing until it's too late.",
  "Don't worry if it doesn't work right. If everything did, you'd be out of a job.",
  "Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.",
  "Programming is usually taught by examples.",
  "Any code of your own that you haven't looked at for six or more months might as well have been written by someone else.",
  "The sooner you start to code, the longer the program will take.",
  "Programming is breaking of one big impossible task into several very small possible tasks.",
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
  "Truth can only be found in one place: the code.",
  "A computer lets you make more mistakes faster than any invention in human history - with the possible exceptions of handguns and tequila.",
  "C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off.",
  "I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.",
  "There is nothing quite so permanent as a quick fix.",
  "The function of good software is to make the complex appear to be simple.",
  "We have to stop optimizing for programmers and start optimizing for users.",
  "The bearing of a child takes nine months, no matter how many women are assigned.",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.",
  "It is easier to change the specification to fit the program than vice versa.",
  "What one programmer can do in one month, two programmers can do in two months.",
  "Inside every large program is a small program struggling to get out.",
  "A language that doesn't affect the way you think about programming is not worth knowing.",
  "UNIX is simple. It just takes a genius to understand its simplicity.",
  "The most important property of a program is whether it accomplishes the intention of its user.",
  "A clever person solves a problem. A wise person avoids it.",
  "Code generation, like drinking alcohol, is good in moderation.",
  "Software undergoes beta testing shortly before it's released. Beta is Latin for 'still doesn't work'.",
  "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.",
  "There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.",
  "Controlling complexity is the essence of computer programming.",
  "The joy of coding Python should be in seeing short, concise, readable classes that express a lot of action in a small amount of clear code - not in reams of trivial code that bores the reader to death.",
  "Computers are good at following instructions, but not at reading your mind.",
  "Learning to code is useful no matter what your career is.",
  "I think everybody in this country should learn how to program a computer because it teaches you how to think.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "No matter how slick the demo is in rehearsal, when you do it in front of a live audience, the probability of a flawless presentation is inversely proportional to the number of people watching.",
  "Any sufficiently advanced bug is indistinguishable from a feature.",
  "I love deadlines. I like the whooshing sound they make as they fly by.",
  "Salesforce limits: keeping developers humble since 1999.",
  "Apex is just Java on a strict diet.",
  "Too many SOQL queries? Time to blame the triggers.",
  "My favorite extreme sport is deploying to production on a Friday.",
  "Clear cache and reload: the IT version of 'have you tried turning it off and on again?'",
  "Working from home means I can complain about my coworkers to my dog.",
  "May your coffee be strong and your build times short.",
  "The Cloud is just someone else's computer.",
  "You are the CSS to my HTML.",
  "Git commit message: 'fixed stuff'.",
  "I don't need a break, I need a breakthrough.",
  "Sleep, eat, code, repeat.",
  "Behind every successful developer is a browser with 50 tabs open.",
  "When nothing goes right, go left, then restart the server.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "If the code works, don't touch it."
];

export const STATIC_FESTIVALS: HighlightEvent[] = [
  { month: 1, day: 1, category: "Global", title: "New Year's Day", description: "The first day of the Gregorian calendar year.", fact: "The earliest known New Year celebrations were in Mesopotamia and date back to 2000 B.C.", quote: "Cheers to a new year and another chance for us to get it right." },
  { month: 1, day: 26, category: "National", title: "Republic Day (India)", description: "Marks the date on which the Constitution of India came into effect.", fact: "The Indian Constitution is the longest written constitution of any sovereign country in the world.", quote: "Let us remember the golden heritage of our country and feel proud to be a part of India." },
  { month: 2, day: 14, category: "Cultural", title: "Valentine's Day", description: "A cultural and commercial celebration of romance and love.", fact: "Approximately 145 million Valentine's Day cards are exchanged annually.", quote: "Love is not finding someone to live with; it's finding someone you can't live without." },
  { month: 3, day: 8, category: "Global", title: "International Women's Day", description: "A global day celebrating the social, economic, cultural, and political achievements of women.", fact: "The first National Woman's Day was observed in the US on February 28, 1909.", quote: "Here's to strong women: may we know them, may we be them, may we raise them." },
  { month: 3, day: 17, category: "Cultural", title: "St. Patrick's Day", description: "A cultural and religious celebration held on the traditional death date of Saint Patrick.", fact: "St. Patrick was actually born in Britain, not Ireland.", quote: "May your pockets be heavy and your heart be light." },
  { month: 4, day: 1, category: "Cultural", title: "April Fools' Day", description: "An annual custom consisting of practical jokes and hoaxes.", fact: "The origins of April Fools' Day are uncertain, though some trace it back to the adoption of the Gregorian calendar in 1582.", quote: "The first of April is the day we remember what we are the other 364 days of the year." },
  { month: 4, day: 22, category: "Global", title: "Earth Day", description: "An annual event to demonstrate support for environmental protection.", fact: "Earth Day went global in 1990, mobilizing 200 million people in 141 countries.", quote: "The Earth does not belong to us: we belong to the Earth." },
  { month: 5, day: 1, category: "Global", title: "International Workers' Day", description: "A celebration of labourers and the working classes.", fact: "The date was chosen to commemorate the Haymarket affair in Chicago in 1886.", quote: "Genius is 1% inspiration and 99% perspiration." },
  { month: 5, day: 4, category: "Cultural", title: "Star Wars Day", description: "An informal commemorative day observed annually to celebrate the Star Wars media franchise.", fact: "The phrase 'May the Fourth be with you' was first used in a political advertisement in 1979.", quote: "May the Force be with you." },
  { month: 6, day: 5, category: "Global", title: "World Environment Day", description: "Encourages worldwide awareness and action for the protection of the environment.", fact: "World Environment Day was established by the UN General Assembly in 1972.", quote: "What we are doing to the forests of the world is but a mirror reflection of what we are doing to ourselves." },
  { month: 6, day: 21, category: "Global", title: "International Day of Yoga", description: "A global celebration of the physical, mental, and spiritual practice of yoga.", fact: "The idea for Yoga Day was proposed by India's Prime Minister Narendra Modi during his 2014 UNGA speech.", quote: "Yoga is the journey of the self, through the self, to the self." },
  { month: 7, day: 4, category: "National", title: "Independence Day (USA)", description: "Commemorates the Declaration of Independence of the United States.", fact: "John Adams believed July 2nd, not July 4th, would be celebrated as Independence Day.", quote: "Liberty is the breath of life to nations." },
  { month: 7, day: 14, category: "National", title: "Bastille Day", description: "The anniversary of the Storming of the Bastille on 14 July 1789, a turning point of the French Revolution.", fact: "The Bastille only held seven prisoners at the time of the storming.", quote: "Liberté, égalité, fraternité." },
  { month: 8, day: 9, category: "Global", title: "International Day of the World's Indigenous Peoples", description: "Promotes and protects the rights of the world's indigenous population.", fact: "There are an estimated 476 million indigenous peoples in the world.", quote: "Our culture is our strength." },
  { month: 8, day: 15, category: "National", title: "Independence Day (India)", description: "Marks the nation's independence from the United Kingdom in 1947.", fact: "The Indian flag was designed by Pingali Venkayya.", quote: "At the stroke of the midnight hour, when the world sleeps, India will awake to life and freedom." },
  { month: 8, day: 26, category: "Global", title: "Women's Equality Day", description: "Commemorates the adoption of the Nineteenth Amendment to the United States Constitution.", fact: "The 19th Amendment was passed by Congress June 4, 1919, and ratified on August 18, 1920.", quote: "Equality is not a concept. It's not something we should be striving for. It's a necessity." },
  { month: 9, day: 21, category: "Global", title: "International Day of Peace", description: "A day dedicated to world peace, specifically the absence of war and violence.", fact: "The UN Peace Bell is rung every year on this day at UN Headquarters in NYC.", quote: "Peace cannot be kept by force; it can only be achieved by understanding." },
  { month: 10, day: 2, category: "National", title: "Gandhi Jayanti", description: "Celebrates the birth anniversary of Mahatma Gandhi.", fact: "The UN declared this day as the International Day of Non-Violence.", quote: "Be the change that you wish to see in the world." },
  { month: 10, day: 31, category: "Cultural", title: "Halloween", description: "A celebration observed in many countries dedicated to remembering the dead.", fact: "Halloween's origins date back to the ancient Celtic festival of Samhain.", quote: "Double, double toil and trouble; Fire burn and caldron bubble." },
  { month: 11, day: 11, category: "National", title: "Veterans Day", description: "Honors military veterans who have served in the United States Armed Forces.", fact: "Veterans Day originated as 'Armistice Day' on Nov 11, 1919.", quote: "Freedom makes a huge requirement of every human being." },
  { month: 11, day: 19, category: "Global", title: "International Men's Day", description: "Celebrates positive male role models and raises awareness of men's issues.", fact: "The themes of IMD include focusing on men's and boys' health.", quote: "A real man loves his wife, and places his family as the most important thing in life." },
  { month: 11, day: 20, category: "Global", title: "Universal Children's Day", description: "Promotes international togetherness, awareness among children worldwide, and improving children's welfare.", fact: "The UN adopted the Declaration of the Rights of the Child on this day in 1959.", quote: "Children are our most valuable resource." },
  { month: 12, day: 1, category: "Global", title: "World AIDS Day", description: "An international day dedicated to raising awareness of the AIDS pandemic.", fact: "World AIDS Day was the first ever global health day, held in 1988.", quote: "Education is the most powerful weapon which you can use to change the world." },
  { month: 12, day: 10, category: "Global", title: "Human Rights Day", description: "Commemorates the day the UN General Assembly adopted the Universal Declaration of Human Rights.", fact: "The Universal Declaration of Human Rights is the most translated document in the world.", quote: "To deny people their human rights is to challenge their very humanity." },
  { month: 12, day: 25, category: "Cultural", title: "Christmas Day", description: "An annual festival commemorating the birth of Jesus Christ.", fact: "The first recorded date of Christmas being celebrated on December 25th was in 336 AD.", quote: "Peace on earth will come to stay, when we live Christmas every day." },
  { month: 12, day: 31, category: "Cultural", title: "New Year's Eve", description: "The last day of the year in the Gregorian calendar.", fact: "The first Times Square New Year's Eve ball drop happened in 1907.", quote: "Tomorrow is the first blank page of a 365-page book. Write a good one." },
  { month: 2, day: 2, category: "Cultural", title: "Groundhog Day", description: "A tradition derived from the Pennsylvania Dutch superstition.", fact: "Punxsutawney Phil has been predicting the weather since 1887.", quote: "Okay, campers, rise and shine, and don't forget your booties 'cause it's cooooold out there today!" },
  { month: 3, day: 14, category: "Global", title: "Pi Day", description: "An annual celebration of the mathematical constant π (pi).", fact: "Pi Day was founded in 1988 by physicist Larry Shaw.", quote: "Mathematics is the language with which God has written the universe." },
  { month: 5, day: 12, category: "Global", title: "International Nurses Day", description: "Celebrated around the world every May 12, the anniversary of Florence Nightingale's birth.", fact: "The International Council of Nurses has celebrated this day since 1965.", quote: "Nurses dispense comfort, compassion, and caring without even a prescription." },
  { month: 10, day: 5, category: "Global", title: "World Teachers' Day", description: "Focuses on appreciating, assessing and improving the educators of the world.", fact: "World Teachers' Day commemorates the anniversary of the adoption of the 1966 ILO/UNESCO Recommendation.", quote: "A good teacher can inspire hope, ignite the imagination, and instill a love of learning." }
];

export const HISTORICAL_EVENTS: HighlightEvent[] = [
  { month: 1, day: 1, historicalYear: 1983, category: "Tech", title: "Internet Born", description: "ARPANET transitions to TCP/IP.", fact: "This day is considered the official birthday of the Internet.", quote: "The Internet is the first thing that humanity has built that humanity doesn't understand." },
  { month: 1, day: 3, historicalYear: 2009, category: "Tech", title: "Bitcoin Genesis Block", description: "Satoshi Nakamoto mines the first block of the Bitcoin blockchain.", fact: "The block contained a headline from The Times about bank bailouts.", quote: "Chancellor on brink of second bailout for banks." },
  { month: 1, day: 9, historicalYear: 2007, category: "Tech", title: "First iPhone Announced", description: "Steve Jobs unveils the original iPhone.", fact: "The phone was described as an iPod, a phone, and an internet communicator.", quote: "An iPod, a phone, and an internet communicator. Are you getting it?" },
  { month: 1, day: 15, historicalYear: 2001, category: "Tech", title: "Wikipedia Launched", description: "Jimmy Wales and Larry Sanger launch Wikipedia.", fact: "Wikipedia was originally intended as a feeder project for Nupedia.", quote: "Imagine a world in which every single person on the planet is given free access to the sum of all human knowledge." },
  { month: 1, day: 24, historicalYear: 1984, category: "Tech", title: "Macintosh Introduced", description: "Apple releases the original Macintosh computer.", fact: "The Macintosh was introduced with the famous '1984' Super Bowl commercial.", quote: "Hello, I am Macintosh." },
  { month: 2, day: 4, historicalYear: 2004, category: "Tech", title: "Facebook Founded", description: "Mark Zuckerberg launches 'TheFacebook' from his Harvard dorm room.", fact: "Membership was initially limited to Harvard students.", quote: "Move fast and break things." },
  { month: 2, day: 14, historicalYear: 1946, category: "Tech", title: "ENIAC Revealed", description: "The world's first general-purpose electronic computer is introduced to the public.", fact: "ENIAC weighed more than 27 tons and took up 1800 square feet.", quote: "A completely new era in computing." },
  { month: 2, day: 18, historicalYear: 1930, category: "Science", title: "Pluto Discovered", description: "Clyde Tombaugh discovers Pluto at the Lowell Observatory.", fact: "Pluto was reclassified as a dwarf planet in 2006.", quote: "It was a tiny point of light, shifting among the stars." },
  { month: 2, day: 24, historicalYear: 1955, category: "Tech", title: "Steve Jobs Born", description: "The co-founder of Apple Inc. was born.", fact: "Jobs was adopted shortly after birth.", quote: "Stay hungry, stay foolish." },
  { month: 3, day: 10, historicalYear: 1876, category: "Tech", title: "First Telephone Call", description: "Alexander Graham Bell makes the first successful telephone call.", fact: "He called to his assistant: 'Mr. Watson, come here, I want to see you.'", quote: "Mr. Watson, come here, I want to see you." },
  { month: 3, day: 12, historicalYear: 1989, category: "Tech", title: "World Wide Web Proposed", description: "Tim Berners-Lee circulates a proposal for 'Information Management'.", fact: "His boss described the proposal as 'vague but exciting'.", quote: "Vague but exciting." },
  { month: 3, day: 21, historicalYear: 2006, category: "Tech", title: "First Tweet", description: "Jack Dorsey sends the first ever tweet.", fact: "The tweet simply read 'just setting up my twttr'.", quote: "just setting up my twttr" },
  { month: 4, day: 1, historicalYear: 1976, category: "Tech", title: "Apple Founded", description: "Steve Jobs, Steve Wozniak, and Ronald Wayne found Apple Computer Inc.", fact: "Wayne sold his share for $800 just 12 days later.", quote: "The people who are crazy enough to think they can change the world are the ones who do." },
  { month: 4, day: 3, historicalYear: 1973, category: "Tech", title: "First Cell Phone Call", description: "Martin Cooper of Motorola makes the first mobile telephone call.", fact: "He called his rival at Bell Labs.", quote: "I'm calling you from a real cellular telephone." },
  { month: 4, day: 4, historicalYear: 1975, category: "Tech", title: "Microsoft Founded", description: "Bill Gates and Paul Allen found Microsoft.", fact: "The company's first product was a BASIC interpreter for the Altair 8800.", quote: "A computer on every desk and in every home." },
  { month: 4, day: 12, historicalYear: 1961, category: "Science", title: "First Human in Space", description: "Yuri Gagarin becomes the first human to journey into outer space.", fact: "His flight lasted 108 minutes.", quote: "I see Earth! It is so beautiful." },
  { month: 4, day: 24, historicalYear: 1990, category: "Science", title: "Hubble Space Telescope Launched", description: "The Space Shuttle Discovery deploys the Hubble Space Telescope.", fact: "A flaw in its mirror was discovered after launch, requiring a repair mission in 1993.", quote: "The universe is a pretty big place." },
  { month: 5, day: 11, historicalYear: 1997, category: "Tech", title: "Deep Blue Beats Kasparov", description: "IBM's Deep Blue defeats world chess champion Garry Kasparov.", fact: "This was the first time a computer defeated a reigning world champion in a standard match.", quote: "I could feel – I could smell – a new kind of intelligence across the table." },
  { month: 5, day: 19, historicalYear: 2001, category: "Tech", title: "First Apple Retail Stores", description: "Apple opens its first two retail stores in Virginia and California.", fact: "Critics predicted the stores would quickly fail.", quote: "A different kind of store." },
  { month: 5, day: 27, historicalYear: 2003, category: "Tech", title: "WordPress Released", description: "Matt Mullenweg and Mike Little release the first version of WordPress.", fact: "Today, WordPress powers over 40% of all websites on the internet.", quote: "Code is poetry." },
  { month: 6, day: 5, historicalYear: 1977, category: "Tech", title: "Apple II Released", description: "The Apple II, one of the first highly successful mass-produced microcomputers, goes on sale.", fact: "It was designed primarily by Steve Wozniak.", quote: "Simplicity is the ultimate sophistication." },
  { month: 6, day: 8, historicalYear: 1955, category: "Tech", title: "Tim Berners-Lee Born", description: "The inventor of the World Wide Web is born.", fact: "He is the director of the World Wide Web Consortium (W3C).", quote: "The Web as I envisaged it, we have not seen it yet." },
  { month: 6, day: 16, historicalYear: 1911, category: "Tech", title: "IBM Founded", description: "Computing-Tabulating-Recording Company is incorporated, later renamed IBM.", fact: "Thomas J. Watson Sr. joined the company in 1914.", quote: "THINK." },
  { month: 6, day: 29, historicalYear: 2007, category: "Tech", title: "iPhone Released", description: "The original iPhone goes on sale in the US.", fact: "Thousands of people lined up outside Apple and AT&T stores days in advance.", quote: "This is a day I've been looking forward to for two and a half years." },
  { month: 7, day: 5, historicalYear: 1994, category: "Tech", title: "Amazon Founded", description: "Jeff Bezos founds Amazon in Bellevue, Washington.", fact: "The company was initially called 'Cadabra'.", quote: "Work hard, have fun, make history." },
  { month: 7, day: 16, historicalYear: 1969, category: "Science", title: "Apollo 11 Launched", description: "The mission to land the first humans on the moon blasts off.", fact: "The Saturn V rocket remains the tallest, heaviest, and most powerful rocket ever brought to operational status.", quote: "Ignition sequence start." },
  { month: 7, day: 20, historicalYear: 1969, category: "Science", title: "First Moon Landing", description: "Neil Armstrong and Buzz Aldrin become the first humans to walk on the moon.", fact: "They spent about two and a quarter hours outside the spacecraft.", quote: "That's one small step for a man, one giant leap for mankind." },
  { month: 8, day: 6, historicalYear: 1991, category: "Tech", title: "World Wide Web Publicly Available", description: "Tim Berners-Lee publishes the first website.", fact: "The first website explained what the World Wide Web was.", quote: "The project is based on the philosophy that much academic information should be freely available to anyone." },
  { month: 8, day: 12, historicalYear: 1981, category: "Tech", title: "IBM PC Introduced", description: "IBM releases the IBM Personal Computer (model 5150).", fact: "It featured an Intel 8088 processor running at 4.77 MHz.", quote: "A computer for everyone." },
  { month: 8, day: 25, historicalYear: 1991, category: "Tech", title: "Linux Kernel Announced", description: "Linus Torvalds announces the Linux project on Usenet.", fact: "He described it as 'just a hobby, won't be big and professional'.", quote: "Hello everybody out there using minix..." },
  { month: 9, day: 4, historicalYear: 1998, category: "Tech", title: "Google Founded", description: "Larry Page and Sergey Brin formally incorporate Google.", fact: "The name Google is a misspelling of 'Googol', the number 1 followed by 100 zeros.", quote: "To organize the world's information and make it universally accessible and useful." },
  { month: 9, day: 9, historicalYear: 1947, category: "Tech", title: "First Computer Bug", description: "Grace Hopper's team discovers a moth in the Harvard Mark II computer.", fact: "They taped the moth into the logbook, coining the term 'debugging'.", quote: "First actual case of bug being found." },
  { month: 9, day: 23, historicalYear: 2008, category: "Tech", title: "Android Launched", description: "The first commercial version of Android (1.0) is released.", fact: "The first Android device was the HTC Dream (T-Mobile G1).", quote: "Openness is key to innovation." },
  { month: 10, day: 4, historicalYear: 1957, category: "Science", title: "Sputnik 1 Launched", description: "The Soviet Union launches the first artificial Earth satellite.", fact: "It transmitted radio signals back to Earth for 21 days.", quote: "The space age has begun." },
  { month: 10, day: 23, historicalYear: 2001, category: "Tech", title: "iPod Introduced", description: "Apple unveils the first iPod.", fact: "It featured a 5GB hard drive that could hold 1,000 songs.", quote: "1,000 songs in your pocket." },
  { month: 10, day: 28, historicalYear: 1955, category: "Tech", title: "Bill Gates Born", description: "The co-founder of Microsoft was born.", fact: "He wrote his first computer program as a young teenager.", quote: "Software is a great combination between artistry and engineering." },
  { month: 10, day: 29, historicalYear: 1969, category: "Tech", title: "First ARPANET Message", description: "The first message is sent over ARPANET from UCLA to SRI.", fact: "The message was meant to be 'login', but the system crashed after 'lo'.", quote: "lo" },
  { month: 11, day: 3, historicalYear: 1957, category: "Science", title: "Laika in Space", description: "The Soviet Union launches Sputnik 2, carrying a dog named Laika.", fact: "Laika was the first living earth-born creature in orbit.", quote: "A small step for a dog." },
  { month: 11, day: 20, historicalYear: 1985, category: "Tech", title: "Windows 1.0 Released", description: "Microsoft releases the first version of Windows.", fact: "It was a graphical shell built on top of MS-DOS.", quote: "A graphical user interface for DOS." },
  { month: 12, day: 9, historicalYear: 1968, category: "Tech", title: "The Mother of All Demos", description: "Douglas Engelbart demonstrates the computer mouse, hypertext, and video conferencing.", fact: "This demo set the stage for modern computing.", quote: "If in your office, you as an intellectual worker were supplied with a computer display..." },
  { month: 12, day: 28, historicalYear: 1969, category: "Tech", title: "Linus Torvalds Born", description: "The creator of the Linux kernel is born in Helsinki, Finland.", fact: "He also created the Git version control system.", quote: "Talk is cheap. Show me the code." },
  { month: 1, day: 19, historicalYear: 1983, category: "Tech", title: "Apple Lisa Introduced", description: "Apple introduces the Lisa, one of the first personal computers to offer a GUI.", fact: "It was named after Steve Jobs' daughter.", quote: "A computer you can use intuitively." },
  { month: 3, day: 6, historicalYear: 1992, category: "Tech", title: "Michelangelo Virus", description: "The Michelangelo computer virus is set to wipe hard drives.", fact: "The media hype far exceeded the actual damage caused.", quote: "The sky is falling!" },
  { month: 5, day: 22, historicalYear: 2010, category: "Tech", title: "Bitcoin Pizza Day", description: "Laszlo Hanyecz purchases two pizzas for 10,000 bitcoins.", fact: "This is widely recognized as the first real-world transaction using Bitcoin.", quote: "I'll pay 10,000 bitcoins for a couple of pizzas." },
  { month: 8, day: 24, historicalYear: 1995, category: "Tech", title: "Windows 95 Released", description: "Microsoft releases Windows 95 to immense fanfare.", fact: "The Rolling Stones' 'Start Me Up' was featured in the ad campaign.", quote: "Start Me Up." },
  { month: 9, day: 15, historicalYear: 1997, category: "Tech", title: "Google.com Registered", description: "The domain name google.com is registered.", fact: "The company itself wouldn't be incorporated for another year.", quote: "Don't be evil." },
  { month: 10, day: 6, historicalYear: 2010, category: "Tech", title: "Instagram Launched", description: "Kevin Systrom and Mike Krieger launch Instagram on iOS.", fact: "It gained one million registered users in 2 months.", quote: "Capture and Share the World's Moments." },
  { month: 11, day: 18, historicalYear: 1992, category: "Tech", title: "Superman Dies (in Comics)", description: "DC Comics publishes the death of Superman, highlighting comic book speculation.", fact: "This is not tech but certainly pop culture history.", quote: "Doomsday." },
  { month: 12, day: 3, historicalYear: 1992, category: "Tech", title: "First SMS Sent", description: "Neil Papworth sends the first text message.", fact: "The message simply read: 'Merry Christmas'.", quote: "Merry Christmas" },
  { month: 12, day: 31, historicalYear: 1999, category: "Tech", title: "Y2K Panic", description: "The world prepares for potential computer chaos as the year changes to 2000.", fact: "Extensive preparation minimized actual disruptions.", quote: "The millennium bug." }
];

